apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: testbuild
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: app
          image: docker.io/gridwhizth/app:latest
          ports:
            - containerPort: 8000
              protocol: TCP

